version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - echo Update npm to latest
      - npm install -g npm@latest
      - cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Starting build `date` `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - echo "Build completed `date`"
      - echo "Starting open-source-dist `date` `pwd`"
      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
      - echo "Open Source Dist completed `date`"
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` `pwd`"
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
    - solutions/**/*
    - fwoa-core/**/*
    - core/**/*
    - deployment/**/*
    - fwoa-tools/**/*
    - fwoa-utilities/**/*
    - solutions/**/*
    - buildspec.yml
    - CHANGELOG.md
    - LICENSE
    - NOTICE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - README.md
    - .github/**/*
    - sonar-project.properties
    - .cfnnag_global_suppress_list