#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: CloudFormation Scanning

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  cfn-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Base Action
        uses: ./.github/actions/baseAction
        
      - name: Build Hapi validator
        run: |
          cd ./fwoa-utilities/javaHapiValidatorLambda
          mvn --batch-mode --update-snapshots --no-transfer-progress clean install
      
      - name: Download US Core IG
        # NOTE if updating the IG version. Please see update implementationGuides.test.ts test too.
        run: |
          mkdir -p implementationGuides
          curl http://hl7.org/fhir/us/core/STU3.1.1/package.tgz | tar xz -C implementationGuides
      
      - name: Compile IGs
        run: yarn run compile-igs

      - name: synthesize smart cdk template for cfn for analysis
        run: |
          cd ./solutions/smart-deployment
          node ../../common/scripts/install-run-rushx.js cdk synth -c issuerEndpoint='test' -c oAuth2ApiEndpoint='test' -c patientPickerEndpoint='test' -c enableSubscriptions=true -c useHapiValidator=true --all --require-approval=never
      - name: cfn_nag on smart cdk template
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./solutions/smart-deployment/cdk.out/smart-fhir-service-dev.template.json
          extra_args:  --blacklist-path ./solutions/smart-deployment/cdk-nag-deny-list.yaml --fail-on-warnings
      - name: synthesize fwoa cdk template for cfn for analysis
        run: |
          cd ./solutions/deployment
          node ../../common/scripts/install-run-rushx.js cdk synth -c enableSubscriptions=true -c useHapiValidator=true --all
      - name: cfn_nag on fwoa cdk template
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./solutions/deployment/cdk.out/fhir-service-dev.template.json
          extra_args:  --blacklist-path ./solutions/deployment/cdk-nag-deny-list.yaml --fail-on-warnings
          
           
          
