#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Code-coverage
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Rush deployment test coverage
        run: |
          cd ./solutions/deployment
          node ../../common/scripts/install-run-rushx.js test-coverage --verbose

      - name: Rush smart-deployment test coverage
        run: |
          cd ./solutions/deployment
          node ../../common/scripts/install-run-rushx.js test-coverage --verbose