name: create-release
on: workflow_dispatch
jobs:
  create-release-branch:
    if: ${{github.ref_name == 'stage'}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: check_admin
        with:
          require: 'admin'
          username: ${{ github.triggering_actor }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: create release branch
        run: |
          echo "Create UUID"
          uuid=`uuidgen`
          echo 'Creating release branch'
          git checkout -b release/$uuid

          echo 'Rush version to bump updates'
          node common/scripts/install-run-rush.js version --bump -b release/$uuid --ignore-git-hooks
  
  create-release-branch-pr-to-main:
    runs-on: ubuntu-20.04
    needs: [create-release-branch]
    outputs:
      pr_number: ${{ steps.open-pr.outputs.pr_number }}
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: create-pull-request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: release-${{ steps.date.outputs.date }}
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
        pr_label: "auto-release-pr"
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

  merge-release-pr-to-main:
    runs-on: ubuntu-20.04
    needs: create-release-branch-pr-to-main
    steps:
      - name: Get PR info
        id: pr_info
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: aws-solutions
          repo: fhir-works-on-aws
          pull_number: ${{ needs.create-release-branch-pr-to-main.outputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: enable merge commits
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: aws-solutions
          repo: fhir-works-on-aws
          allow_merge_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: merge release branch pr to main
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge
          owner: aws-solutions
          repo: fhir-works-on-aws
          pull_number: ${{ inputs.pr_number }}
          merge_method: 'merge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: disable merge commits
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: aws-solutions
          repo: fhir-works-on-aws
          allow_merge_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
