name: Publish-and-merge-to-develop
on:  
  pull_request_target:
    types:
      - closed
    branches:
      - copy-main

jobs:
  rush-publish:
    # if: github.event.pull_request.merged == true && vars.PUBLISH_TO_NPM == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Set git config
        run: |
          git config user.email ${{ vars.BOT_USER_EMAIL }}
          git config user.name ${{ vars.BOT_USER_NAME }}
      
      - name: Rush Publish
        run: |
          PUBLISH_CMD="--add-commit-details --apply --npm-auth-token ${{ secrets.NPM_AUTH_TOKEN }} --ignore-git-hooks --include-all --set-access-level public --target-branch copy-main --publish"
          node common/scripts/install-run-rush.js publish $PUBLISH_CMD
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}