#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: test secrets input for reusable workflow
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
jobs:  
  pre-deployment-check:
    name: Pre deployment check
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Block Concurrent Deployments
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-fhir:
    uses:
      ./.github/workflows/deploy.yaml  
    secrets: inherit 
  deploy-smart-fhir:
    uses:
      ./.github/workflows/deploy-smart.yaml  
    secrets: inherit 
