name: Verify Changefiles
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - develop

jobs:
  run-rush-change-verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Rush verify changes
        run: |
          echo "checking if all changefiles were created"          
          node common/scripts/install-run-rush.js change --verify -b origin/develop